REPLACE INTO `role` VALUES (1,'STUDENT');
REPLACE INTO `role` VALUES (2,'FACULTY');
REPLACE INTO `role` VALUES (3,'ADMIN');
-- INSERT INTO USER (user_id, Active, USERNAME, PASSWORD)
-- -- VALUES (3,1,'bruckgmk@gmail.com', '123456');